//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class MSleep : MachineState
{ 
	private int duration;
	public MSleep (int duration)
	{
			this.startTime = -1;
			this.duration = duration;
	}
	public override ResultState Tick ()
	{	
		int currentTime = Environment.TickCount & Int32.MaxValue;
		if (this.startTime == -1) {
			startTime = currentTime;
		}
		if ((currentTime - startTime) > this.duration) {
			return ResultState.Finished;
		}
		return ResultState.Notfinished;
	}
}
